<ul id="mailbox-menu">
	<li><a class="inbox" href="inbox.jsp?cat=mail">Inkorg <span>(2)</span></a></li>
	<li><a class="pickups" href="inbox.jsp?cat=ragg">Ragg <span>(5)</span></a></li>
	<li><a class="ad_answers" href="inbox.jsp?cat=ads">Annonssvar <span>(0)</span></a></li>
	<li><a class="sent" href="inbox.jsp?cat=sent">Skickat</a></li>
	<li><a class="help support-mail" href="#">Hjälp &amp; Support</a></li>
</ul>
