<div id="mailbox-categories">

    <span id="mailbox-categories-list-heading">Visa: </span>
    <ul id="mailbox-categories-list">
        <li class="mailbox-categories-list-item"><a href="?cat=mail&filter=all" class="active">Alla</a></li>
        <li class="mailbox-categories-list-item">|</li>
        <li class="mailbox-categories-list-item"><a href="?cat=mail&filter=unread">Olästa</a></li>
    </ul>
</div>
