<div class="nav-main">
    <ul id="nav1">
              <li ><a class="" href="profile.jsp"><span class="left">&nbsp;</span><span>Min sida</span>   <span class="right">&nbsp;</span></a></li>
              <li ><a class="" href="search.jsp">   <span class="left">&nbsp;</span><span>Sök</span>        <span class="right">&nbsp;</span></a></li>
              <li ><a class="" href="ads.jsp">      <span class="left">&nbsp;</span><span>Annonser</span>   <span class="right">&nbsp;</span></a></li>
              <li ><a class="" href="gallery.jsp">  <span class="left">&nbsp;</span><span>Bilder</span>     <span class="right">&nbsp;</span></a></li>
              <li ><a class="" href="#">            <span class="left">&nbsp;</span><span>Logout</span>     <span class="right">&nbsp;</span></a></li>
    </ul>
</div>

