<div style="top: 100px; visibility: visible;" id="registerModal" class="reveal-modal"><div class="box be_a_member">
	<div class="base">
		<h1>Bli medlem</h1>
		<form id="userRegistration" enctype="application/x-www-form-urlencoded" action="/registration/process" method="post"><dl class="zend_form">
<dt id="Registration-label">&nbsp;</dt><dd id="Registration-element"><fieldset id="fieldset-Registration"><legend>Registrera dig</legend>
<dl>
<div class="element"><div id="username-label"><label for="username" class="form-lbl required">Användarnamn:</label></div>
<div>
<input name="username" id="username" value="" type="text"></div></div>
<div class="element"><div id="email-label"><label for="email" class="form-lbl required">Epostadress:</label></div>
<div>
<input name="email" id="email" value="" type="text"></div></div>
<div class="element"><div id="password-label"><label for="password" class="form-lbl required">Lösenord:</label></div>
<div>
<input name="password" id="password" value="" type="password"></div></div>
<div class="element"><div id="confirmation-label"><label for="confirmation" class="form-lbl required">Jag är över 18 år och godkänner medlemsavtalet &amp; villkoren</label></div>
<div>
<input name="confirmation" value="" type="hidden"><input name="confirmation" id="confirmation" value="1" checked="checked" type="checkbox"></div></div></dl></fieldset></dd>
<dt id="save-label">&nbsp;</dt><dd id="save-element">
<input name="save" id="save" value="Fortsätt" type="submit"></dd></dl></form>	</div>
</div><a class="close-reveal-modal">×</a></div>
