<div id="user-options">

    <div>Erotikfilter <a href="#" class="poptip" title="Aktiverar du erotikfiltret censureras erotiskt material på sajten.">
        <img class="questionmark" src="/img/questionmark.png" alt="?" /></a>
    </div>
		<a href="" id="toggle-explicit-content" class="active" title="Visa inte stötande material"><span>&nbsp;</span></a>

</div>

<ul id="dashboard-counts">
	<li class="active">
		<a href="mail.jsp" class="mail">
               <span id="mail"><!-- Messages--></span> Mejl</a>
    </li>

	<li class="active">
		<a href="#" class="flirts">
               <span id="flirts"><!-- Flirts--></span> Ragg</a>
    </li>

	<li class="active">
		<a href="#" class="post">
               <span id="posts"><!-- Posts--></span> Gästbok</a>
    </li>

	<li class="active">
		<a href="#" class="visit">
               <span id="visits"><!-- Visits--></span> Besök</a>
    </li>

	<li>
		<a href="#" class="favorite">
               <span id="online"><!-- Online--></span> Online</a>
    </li>
</ul>
