package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    DataReference - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class DataReferenceTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Data Reference";
    public static final String TABLE = "DataReference";
    private static final String DESCRIPTION = "this is the description";

    public enum Columns {Location, name, Time, Birth, Occurrences, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Location", DataColumn.noFormatting),
            new ReferenceColumn("name", DataColumn.noFormatting, new TableReference("Example1", "Name")),
            new TimeStampColumn("Time", DataColumn.noFormatting),
            new DateColumn("Birth", DataColumn.noFormatting),
            new IntColumn("Occurrences", DataColumn.noFormatting),
    };

    private static final DataReference associatedObject = new DataReference();
    public DataReferenceTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
        nameColumn = 1;
        // Not set as external
        // Not a constant table
    }

    public DataReferenceTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"test loc", "linus", "2014-07-01 01:02:03", "2014-07-01", "1", "system"},



    };

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/




}
