package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    Example3 - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class Example3 extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new Example3Table();

    public Example3(){

        super();         if(table == null)
            table = TABLE;
    }

    public Example3(String name, String longtext, String bloblength, long number, boolean isactive, String last, String first) throws BackOfficeException{

        this();
        ColumnStructureInterface[] columns = getColumnFromTable();


        data = new ColumnDataInterface[columns.length + 1];

        data[0] = new StringData(name);
        data[1] = new TextData(longtext);
        data[2] = new BlobData(bloblength);
        data[3] = new IntData(number);
        data[4] = new BoolData(isactive);
        data[5] = new TimeStampData(last);
        data[6] = new DateData(first);

        data[7] = new IntData( 0 ); // Set id
        exists = true;


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public Example3(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        return new Example3(data[0].getStringValue(), data[1].getStringValue(), data[2].getStringValue(), data[3].getIntValue(), data[4].getBoolValue(), data[5].getStringValue(), data[6].getStringValue());
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public String getLongText(){

        TextData data = (TextData) this.data[1];
        return data.getStringValue();
    }

    public void setLongText(String longtext){

        TextData data = (TextData) this.data[1];
        data.setStringValue(longtext);
    }



    public String getBlobLength(){

        BlobData data = (BlobData) this.data[2];
        return data.getStringValue();
    }

    public void setBlobLength(String bloblength){

        BlobData data = (BlobData) this.data[2];
        data.setStringValue(bloblength);
    }



    public long getNumber(){

        IntData data = (IntData) this.data[3];
        return data.value;
    }

    public void setNumber(long number){

        IntData data = (IntData) this.data[3];
        data.value = number;
    }



    public boolean getisActive(){

        BoolData data = (BoolData) this.data[4];
        return data.value;
    }

    public void setisActive(boolean isactive){

        BoolData data = (BoolData) this.data[4];
        data.value = isactive;
    }



    public DBTimeStamp getlast()throws BackOfficeException{

        TimeStampData data = (TimeStampData) this.data[5];
        return new DBTimeStamp(DBTimeStamp.SQL_TIMESTAMP, data.value);
    }

    public void setlast(DBTimeStamp last){

        TimeStampData data = (TimeStampData) this.data[5];
        data.value = last.getSQLTime().toString();
    }



    public DBTimeStamp getfirst()throws BackOfficeException{

        DateData data = (DateData) this.data[6];
        return new DBTimeStamp(DBTimeStamp.ISO_DATE, data.value);
    }

    public void setfirst(DBTimeStamp first){

        DateData data = (DateData) this.data[6];
        data.value = first.getISODate().toString();
    }




    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
