package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    ExamplePivotSecondary - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ExamplePivotSecondaryTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Pivot";
    public static final String TABLE = "ExamplePivotSecondary";
    private static final String DESCRIPTION = "this is a secondary table linked from the primary";

    public enum Columns {Name, Origin, BHP, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new StringColumn("Origin", DataColumn.noFormatting),
            new IntColumn("BHP", DataColumn.noFormatting),
    };

    private static final ExamplePivotSecondary associatedObject = new ExamplePivotSecondary();
    public ExamplePivotSecondaryTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ExamplePivotSecondaryTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"ford", "us", "220", "system"},
          {"renault", "france", "165", "system"},
          {"buick", "us", "100", "system"},
          {"bmw", "germany", "300", "system"},



    };

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
