package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    ExamplePivotSecondary - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ExamplePivotSecondary extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new ExamplePivotSecondaryTable();

    public ExamplePivotSecondary(){

        super();         if(table == null)
            table = TABLE;
    }

    public ExamplePivotSecondary(String name, String origin, long bhp) throws BackOfficeException{

        this();
        ColumnStructureInterface[] columns = getColumnFromTable();


        data = new ColumnDataInterface[columns.length + 1];

        data[0] = new StringData(name);
        data[1] = new StringData(origin);
        data[2] = new IntData(bhp);

        data[3] = new IntData( 0 ); // Set id
        exists = true;


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public ExamplePivotSecondary(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        return new ExamplePivotSecondary(data[0].getStringValue(), data[1].getStringValue(), data[2].getIntValue());
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public String getOrigin(){

        StringData data = (StringData) this.data[1];
        return data.getStringValue();
    }

    public void setOrigin(String origin){

        StringData data = (StringData) this.data[1];
        data.setStringValue(origin);
    }



    public long getBHP(){

        IntData data = (IntData) this.data[2];
        return data.value;
    }

    public void setBHP(long bhp){

        IntData data = (IntData) this.data[2];
        data.value = bhp;
    }




    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
