package system.tables;

import dataRepresentation.*;

import java.util.Map;

import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    Example1 - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class Example1Table extends DataTable implements DataTableInterface{

    private static final String TITLE = "Example Table";
    public static final String TABLE = "Example1";
    private static final String DESCRIPTION = "Example Data Object (generated)";

    public enum Columns {Name, Number, isActive, Status, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("Number", DataColumn.noFormatting),
            new BoolColumn("isActive", DataColumn.noFormatting),
            new IntColumn("Status", DataColumn.noFormatting),
    };

    private static final Example1 associatedObject = new Example1();
    public Example1Table(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        setIsConstant();
    }

    public Example1Table(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"linus", "4711", "true", "1", "system"},



    };

    private static Map<String, String> constantMap = null;


    @Override
    public Map<String, String> getConstantMap(){

        if(constantMap == null)
            constantMap = asNameMap();
        return constantMap;

    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
