package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    ExamplePivotObject - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ExamplePivotObjectTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Pivot";
    public static final String TABLE = "ExamplePivotObject";
    private static final String DESCRIPTION = "this is the description of the pivot table";

    public enum Columns {Name, Country, Comission, Make, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new StringColumn("Country", DataColumn.noFormatting),
            new DateColumn("Comission", DataColumn.noFormatting),
            new ReferenceColumn("Make", DataColumn.noFormatting, new TableReference("ExamplePivotSecondary", "Name")),
    };

    private static final ExamplePivotObject associatedObject = new ExamplePivotObject();
    public ExamplePivotObjectTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ExamplePivotObjectTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"linus", "sweden", "2002-01-01", "ford", "system"},
          {"linus", "sweden", "2004-01-20", "renault", "system"},
          {"mark", "us", "1963-08-13", "buick", "system"},
          {"franz", "germany", "2002-10-10", "bmw", "system"},



    };

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/




}
