package system.tables;

import dataRepresentation.*;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;

/********************************************************
 *
 *    Example1 - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class Example1 extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new Example1Table();

    public Example1(){

        super();         if(table == null)
            table = TABLE;
    }

    public Example1(String name, long number, boolean isactive, long status) throws BackOfficeException{

        this();
        ColumnStructureInterface[] columns = getColumnFromTable();


        data = new ColumnDataInterface[columns.length + 1];

        data[0] = new StringData(name);
        data[1] = new IntData(number);
        data[2] = new BoolData(isactive);
        data[3] = new IntData(status);

        data[4] = new IntData( 0 ); // Set id
        exists = true;


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public Example1(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        return new Example1(data[0].getStringValue(), data[1].getIntValue(), data[2].getBoolValue(), data[3].getIntValue());
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public long getNumber(){

        IntData data = (IntData) this.data[1];
        return data.value;
    }

    public void setNumber(long number){

        IntData data = (IntData) this.data[1];
        data.value = number;
    }



    public boolean getisActive(){

        BoolData data = (BoolData) this.data[2];
        return data.value;
    }

    public void setisActive(boolean isactive){

        BoolData data = (BoolData) this.data[2];
        data.value = isactive;
    }



    public long getStatus(){

        IntData data = (IntData) this.data[3];
        return data.value;
    }

    public void setStatus(long status){

        IntData data = (IntData) this.data[3];
        data.value = status;
    }




    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
